(function () {
const languages = [
  "中文",
  "英语",
  "日语",
  "韩语",
  "法语",
  "德语",
  "西班牙语",
  "俄语",
  "阿拉伯语",
  "葡萄牙语",
];

const customLanguageNames = new Set([
  ...languages,
  "越南语",
  "泰语",
  "印尼语",
  "马来语",
  "土耳其语",
  "意大利语",
  "荷兰语",
  "波兰语",
  "乌克兰语",
  "希伯来语",
  "印地语",
  "孟加拉语",
  "乌尔都语",
  "波斯语",
  "希腊语",
  "瑞典语",
  "挪威语",
  "丹麦语",
  "芬兰语",
  "捷克语",
  "匈牙利语",
  "罗马尼亚语",
  "保加利亚语",
  "塞尔维亚语",
  "克罗地亚语",
  "斯洛伐克语",
  "斯洛文尼亚语",
  "立陶宛语",
  "拉脱维亚语",
  "爱沙尼亚语",
  "斯瓦希里语",
  "菲律宾语",
  "他加禄语",
  "缅甸语",
  "高棉语",
  "老挝语",
  "蒙古语",
  "尼泊尔语",
  "僧伽罗语",
  "泰米尔语",
  "泰卢固语",
  "马拉地语",
  "古吉拉特语",
  "旁遮普语",
  "加拿大语",
  "马拉雅拉姆语",
  "阿姆哈拉语",
  "豪萨语",
  "约鲁巴语",
  "祖鲁语",
  "南非荷兰语",
  "加泰罗尼亚语",
  "巴斯克语",
  "加利西亚语",
  "爱尔兰语",
  "威尔士语",
  "冰岛语",
  "马耳他语",
  "阿尔巴尼亚语",
  "马其顿语",
  "格鲁吉亚语",
  "亚美尼亚语",
  "阿塞拜疆语",
  "哈萨克语",
  "乌兹别克语",
  "吉尔吉斯语",
  "塔吉克语",
  "普什图语",
  "库尔德语",
  "索马里语",
  "拉丁语",
  "世界语",
]);

const DEFAULT_UI_LANGUAGE = "en";
const uiLanguages = [
  { code: "en", label: "English", htmlLang: "en" },
  { code: "zh-CN", label: "简体中文", htmlLang: "zh-CN" },
  { code: "ja", label: "日本語", htmlLang: "ja" },
  { code: "ko", label: "한국어", htmlLang: "ko" },
  { code: "fr", label: "Français", htmlLang: "fr" },
  { code: "de", label: "Deutsch", htmlLang: "de" },
  { code: "es", label: "Español", htmlLang: "es" },
  { code: "pt", label: "Português", htmlLang: "pt" },
  { code: "ru", label: "Русский", htmlLang: "ru" },
  { code: "ar", label: "العربية", htmlLang: "ar" },
];

const languageLocaleCodes = {
  中文: "zh",
  英语: "en",
  日语: "ja",
  韩语: "ko",
  法语: "fr",
  德语: "de",
  西班牙语: "es",
  俄语: "ru",
  阿拉伯语: "ar",
  葡萄牙语: "pt",
  越南语: "vi",
  泰语: "th",
  印尼语: "id",
  马来语: "ms",
  土耳其语: "tr",
  意大利语: "it",
  荷兰语: "nl",
  波兰语: "pl",
  乌克兰语: "uk",
  希伯来语: "he",
  印地语: "hi",
  孟加拉语: "bn",
  乌尔都语: "ur",
  波斯语: "fa",
  希腊语: "el",
  瑞典语: "sv",
  挪威语: "no",
  丹麦语: "da",
  芬兰语: "fi",
  捷克语: "cs",
  匈牙利语: "hu",
  罗马尼亚语: "ro",
  保加利亚语: "bg",
  塞尔维亚语: "sr",
  克罗地亚语: "hr",
  斯洛伐克语: "sk",
  斯洛文尼亚语: "sl",
  立陶宛语: "lt",
  拉脱维亚语: "lv",
  爱沙尼亚语: "et",
  斯瓦希里语: "sw",
  菲律宾语: "fil",
  他加禄语: "tl",
  缅甸语: "my",
  高棉语: "km",
  老挝语: "lo",
  蒙古语: "mn",
  尼泊尔语: "ne",
  僧伽罗语: "si",
  泰米尔语: "ta",
  泰卢固语: "te",
  马拉地语: "mr",
  古吉拉特语: "gu",
  旁遮普语: "pa",
  加拿大语: "kn",
  马拉雅拉姆语: "ml",
  阿姆哈拉语: "am",
  豪萨语: "ha",
  约鲁巴语: "yo",
  祖鲁语: "zu",
  南非荷兰语: "af",
  加泰罗尼亚语: "ca",
  巴斯克语: "eu",
  加利西亚语: "gl",
  爱尔兰语: "ga",
  威尔士语: "cy",
  冰岛语: "is",
  马耳他语: "mt",
  阿尔巴尼亚语: "sq",
  马其顿语: "mk",
  格鲁吉亚语: "ka",
  亚美尼亚语: "hy",
  阿塞拜疆语: "az",
  哈萨克语: "kk",
  乌兹别克语: "uz",
  吉尔吉斯语: "ky",
  塔吉克语: "tg",
  普什图语: "ps",
  库尔德语: "ku",
  索马里语: "so",
  拉丁语: "la",
  世界语: "eo",
};

const uiText = {
  en: {
    "app.subtitle": "Bilingual translation for conversation records",
    "settings": "Settings",
    "newProject": "+ New project",
    "api.unset": "API not set",
    "pullSync": "Pull sync",
    "recent": "Recent",
    "archiveFolder": "Archive folder",
    "currentProject": "Current project",
    "noProject": "No project yet",
    "selectProjectFirst": "Create or select a project first",
    "backProjectList": "Back to project list",
    "empty.title": "Create a conversation project first",
    "empty.description": "For example, create “Chat with a French friend”, choose two languages, then translate with side-by-side bubbles.",
    "autoDetectInput": "Auto-detect input language",
    "waitingInput": "Waiting for input",
    "source.placeholder": "Enter one message, for example: Hello, nice to meet you.",
    "translate.submit": "Translate and add to conversation",
    "translate.loading": "Translating...",
    "translate.translating": "Translating: {label}",
    "translate.failed": "Translation failed: {label}",
    "translate.done": "Done: {label}",
    "waitingProject": "Waiting for project",
    "detected.manualTitle": "Direction manually swapped for this input",
    "detected.autoTitle": "Click to swap direction for this input",
    "projectDialog.newTitle": "New project",
    "projectDialog.editTitle": "Project settings",
    "projectName": "Project name",
    "projectName.placeholder": "For example: Chat with a French friend",
    "languageLeft": "Language - left",
    "languageRight": "Language - right",
    "customLanguage.placeholder.a": "Enter a language, for example: Vietnamese",
    "customLanguage.placeholder.b": "Enter a language, for example: Turkish",
    "language.reviewing": "Reviewing custom language...",
    "cancel": "Cancel",
    "create": "Create",
    "save": "Save",
    "settings.title": "Settings",
    "settings.subtitle": "Model API, backup API, sync, and interface language",
    "settings.uiLanguage": "Interface language",
    "settings.tab.primary": "Primary API",
    "settings.tab.backup": "Backup API",
    "settings.tab.proxy": "Local proxy",
    "settings.tab.sync": "Sync",
    "settings.tab.files": "Files",
    "provider": "Provider",
    "apiKey": "API Key",
    "showApiKey": "Show API Key",
    "showSecret": "Show secret",
    "hideSecret": "Hide secret",
    "model": "Model",
    "loadModels": "Load models",
    "qwenHint": "Pixel Penguin strongly recommends the QWEN-MT-TURBO model.",
    "manualModel": "Manual model",
    "baseUrl": "Base URL",
    "translationStyle": "Translation style",
    "style.faithful": "Business literal: stay close to the source",
    "style.natural": "Natural business: lightly polished",
    "style.concise": "Concise: compress the expression",
    "showTokenUsage": "Show token usage",
    "backup.enable": "Enable backup API",
    "backup.apiKey.placeholder": "Backup API Key",
    "backup.hint": "After the primary API times out 3 times in a row for one translation, the backup API is used temporarily. The next translation still tries the primary API first.",
    "proxy.enable": "Enable local proxy settings",
    "proxy.type": "Type",
    "proxy.port": "Port",
    "proxy.host": "Host",
    "proxy.hint": "Browsers cannot assign SOCKS5/HTTP proxies directly to fetch. This setting is saved for a future local proxy bridge or native app.",
    "sync.enable": "Enable project sync",
    "sync.method": "Sync method",
    "sync.gist": "Private GitHub Gist sync",
    "sync.custom": "Custom sync service",
    "sync.endpoint": "Gist ID / sync service URL",
    "sync.endpoint.placeholder": "Leave empty to create one on first upload, or enter a Gist ID / custom service URL",
    "sync.endpoint.customPlaceholder": "https://your-server.example.com",
    "sync.token": "Access token / GitHub Token",
    "sync.token.placeholder": "GitHub token, or auth token for your custom service",
    "sync.token.customPlaceholder": "Optional token for your server",
    "sync.showToken": "Show access token",
    "sync.onOpen": "Sync once when opening a project",
    "sync.afterMessage": "Upload once after adding a translation",
    "sync.hint": "Private GitHub Gist sync is recommended: old device uploads all, new device uses the same Token and Gist ID to pull.",
    "files.enable": "Enable Markdown file saving",
    "files.chooseFolder": "Connect records folder",
    "files.import": "Read local records",
    "files.saveAll": "Save all now",
    "files.status": "Choose the “对话记录” folder in Edge. Each project is saved as a folder containing `对话.md`.",
    "settings.status": "API keys are stored locally in this browser.",
    "test.connection": "Test connection",
    "test.backup": "Test backup",
    "test.sync": "Test sync",
    "sync.uploadAll": "Upload all",
    "customLanguage": "Custom language",
    "manualInput": "Manual input",
    "project.edit": "Edit project",
    "project.swapLanguages": "Swap language direction",
    "project.resetPrompt": "Reset prompt",
    "project.pin": "Pin",
    "project.unpin": "Unpin",
    "project.archive": "Archive",
    "project.unarchive": "Move out of archive",
    "project.delete": "Delete project",
    "project.emptyRecent": "No recent conversations",
    "project.swapped": "Swapped to: {label}",
    "translation.autoCorrected": "Direction corrected automatically: {label}",
    "translation.saveFailed": "Translated, but saving failed. This message may disappear after reload.",
    "uiLanguage.saved": "Interface language saved.",
    "settings.saved": "Settings saved.",
    "project.formInvalid": "Enter a project name and choose two different languages.",
    "project.updated": "Project updated.",
    "project.created": "Project created.",
    "language.reviewFailed": "Language review failed. Please try again later.",
    "language.notFound": "That language was not found.",
  },
  "zh-CN": {
    "app.subtitle": "用对话记录双语翻译",
    "settings": "设置",
    "newProject": "+ 新建项目",
    "api.unset": "API 未设置",
    "pullSync": "拉取同步",
    "recent": "最近",
    "archiveFolder": "归档文件夹",
    "currentProject": "当前项目",
    "noProject": "还没有项目",
    "selectProjectFirst": "请先新建或选择项目",
    "backProjectList": "返回项目列表",
    "empty.title": "先创建一个对话项目",
    "empty.description": "例如“和日本客户沟通”，选择中文和日语，然后就可以开始左右对照翻译。",
    "autoDetectInput": "自动识别输入语言",
    "waitingInput": "等待输入",
    "source.placeholder": "输入一句对话，例如：你好，很高兴认识你。",
    "translate.submit": "翻译并加入对话",
    "translate.loading": "翻译中...",
    "translate.translating": "正在翻译：{label}",
    "translate.failed": "翻译失败：{label}",
    "translate.done": "已完成：{label}",
    "waitingProject": "等待项目",
    "detected.manualTitle": "已临时切换本次翻译方向",
    "detected.autoTitle": "点击临时交换本次翻译方向",
    "projectDialog.newTitle": "新建项目",
    "projectDialog.editTitle": "项目设置",
    "projectName": "项目名称",
    "projectName.placeholder": "例如：和法国朋友聊天",
    "languageLeft": "语言-左",
    "languageRight": "语言-右",
    "customLanguage.placeholder.a": "输入语言，例如：越南语",
    "customLanguage.placeholder.b": "输入语言，例如：土耳其语",
    "language.reviewing": "正在审核自定义语言...",
    "cancel": "取消",
    "create": "创建",
    "save": "保存",
    "settings.title": "设置",
    "settings.subtitle": "模型 API、备用 API、同步和界面语言",
    "settings.uiLanguage": "界面语言",
    "settings.tab.primary": "主 API",
    "settings.tab.backup": "备用 API",
    "settings.tab.proxy": "本地代理",
    "settings.tab.sync": "同步",
    "settings.tab.files": "文件",
    "provider": "服务商",
    "apiKey": "API Key",
    "showApiKey": "显示 API Key",
    "showSecret": "显示密钥",
    "hideSecret": "隐藏密钥",
    "model": "模型",
    "loadModels": "读取模型",
    "qwenHint": "像素企鹅强烈推荐使用 QWEN-MT-TURBO 模型",
    "manualModel": "手动模型",
    "baseUrl": "Base URL",
    "translationStyle": "翻译风格",
    "style.faithful": "商务直译：尽量贴近原文",
    "style.natural": "自然商务：轻微润色",
    "style.concise": "简洁：压缩表达",
    "showTokenUsage": "显示 Token 使用量",
    "backup.enable": "启用备用 API",
    "backup.apiKey.placeholder": "备用 API Key",
    "backup.hint": "主 API 单次翻译连续超时 3 次后，会临时使用备用 API；下一次翻译仍先尝试主 API。",
    "proxy.enable": "启用本地代理配置",
    "proxy.type": "类型",
    "proxy.port": "端口",
    "proxy.host": "主机",
    "proxy.hint": "浏览器网页不能直接为 fetch 指定 SOCKS5/HTTP 代理；这里会保存配置，供之后的本地代理桥或苹果 App 使用。",
    "sync.enable": "启用项目内容同步",
    "sync.method": "同步方式",
    "sync.gist": "GitHub Gist 私有同步",
    "sync.custom": "自定义同步服务",
    "sync.endpoint": "Gist ID / 同步服务地址",
    "sync.endpoint.placeholder": "留空可首次上传时自动创建，或填 Gist ID / 自定义服务地址",
    "sync.endpoint.customPlaceholder": "https://your-server.example.com",
    "sync.token": "访问令牌 / GitHub Token",
    "sync.token.placeholder": "GitHub token，或自定义服务鉴权 token",
    "sync.token.customPlaceholder": "可选，用于你的服务器鉴权",
    "sync.showToken": "显示访问令牌",
    "sync.onOpen": "打开项目时同步一次",
    "sync.afterMessage": "新增翻译后上传一次",
    "sync.hint": "推荐使用 GitHub Gist 私有同步：老设备点“上传全部”，新设备填同一个 Token 和 Gist ID 后点“拉取同步”。",
    "files.enable": "启用 Markdown 文件保存",
    "files.chooseFolder": "连接对话记录文件夹",
    "files.import": "读取本地记录",
    "files.saveAll": "立即保存全部",
    "files.status": "请在 Edge 中选择项目里的“对话记录”文件夹。每个项目会保存为一个文件夹，里面包含 `对话.md`。",
    "settings.status": "API Key 会保存在当前浏览器本地。",
    "test.connection": "测试连接",
    "test.backup": "测试备用",
    "test.sync": "测试同步",
    "sync.uploadAll": "上传全部",
    "customLanguage": "自定义语言",
    "manualInput": "手动输入",
    "project.edit": "编辑项目",
    "project.swapLanguages": "互换语言方向",
    "project.resetPrompt": "重置提示词",
    "project.pin": "置顶",
    "project.unpin": "取消置顶",
    "project.archive": "归档",
    "project.unarchive": "移出归档",
    "project.delete": "删除项目",
    "project.emptyRecent": "暂无最近对话",
    "project.swapped": "已切换为：{label}",
    "translation.autoCorrected": "已自动修正方向：{label}",
    "translation.saveFailed": "已翻译，但保存失败；刷新后这条消息可能会消失。",
    "uiLanguage.saved": "界面语言已保存。",
    "settings.saved": "设置已保存。",
    "project.formInvalid": "请填写项目名称，并选择两种不同语言。",
    "project.updated": "项目已更新。",
    "project.created": "项目已创建。",
    "language.reviewFailed": "语言审核失败，请稍后再试。",
    "language.notFound": "没有该语言。",
  },
  ja: {
    "settings": "設定", "newProject": "+ 新規プロジェクト", "api.unset": "API 未設定", "pullSync": "同期を取得", "recent": "最近", "archiveFolder": "アーカイブ", "currentProject": "現在のプロジェクト", "noProject": "プロジェクトはまだありません", "selectProjectFirst": "先にプロジェクトを作成または選択してください", "autoDetectInput": "入力言語を自動検出", "waitingInput": "入力待ち", "translate.submit": "翻訳して会話に追加", "settings.title": "設定", "settings.subtitle": "モデル API、同期、表示言語", "settings.uiLanguage": "表示言語", "settings.tab.primary": "メイン API", "settings.tab.backup": "予備 API", "settings.tab.proxy": "ローカルプロキシ", "settings.tab.sync": "同期", "settings.tab.files": "ファイル", "projectDialog.newTitle": "新規プロジェクト", "projectDialog.editTitle": "プロジェクト設定", "projectName": "プロジェクト名", "languageLeft": "左の言語", "languageRight": "右の言語", "cancel": "キャンセル", "create": "作成", "save": "保存", "provider": "プロバイダー", "apiKey": "API Key", "model": "モデル", "loadModels": "モデルを読み込む", "manualModel": "手動モデル", "translationStyle": "翻訳スタイル", "test.connection": "接続テスト", "test.backup": "予備をテスト", "test.sync": "同期テスト", "sync.uploadAll": "すべてアップロード", "uiLanguage.saved": "表示言語を保存しました。"
  },
  ko: {
    "settings": "설정", "newProject": "+ 새 프로젝트", "api.unset": "API 미설정", "pullSync": "동기화 가져오기", "recent": "최근", "archiveFolder": "보관 폴더", "currentProject": "현재 프로젝트", "noProject": "아직 프로젝트 없음", "selectProjectFirst": "먼저 프로젝트를 만들거나 선택하세요", "autoDetectInput": "입력 언어 자동 감지", "waitingInput": "입력 대기", "translate.submit": "번역 후 대화에 추가", "settings.title": "설정", "settings.subtitle": "모델 API, 동기화, 인터페이스 언어", "settings.uiLanguage": "인터페이스 언어", "settings.tab.primary": "기본 API", "settings.tab.backup": "백업 API", "settings.tab.proxy": "로컬 프록시", "settings.tab.sync": "동기화", "settings.tab.files": "파일", "projectDialog.newTitle": "새 프로젝트", "projectDialog.editTitle": "프로젝트 설정", "projectName": "프로젝트 이름", "languageLeft": "왼쪽 언어", "languageRight": "오른쪽 언어", "cancel": "취소", "create": "만들기", "save": "저장", "provider": "제공자", "apiKey": "API Key", "model": "모델", "loadModels": "모델 불러오기", "manualModel": "수동 모델", "translationStyle": "번역 스타일", "test.connection": "연결 테스트", "test.backup": "백업 테스트", "test.sync": "동기화 테스트", "sync.uploadAll": "모두 업로드", "uiLanguage.saved": "인터페이스 언어가 저장되었습니다."
  },
  fr: {
    "settings": "Réglages", "newProject": "+ Nouveau projet", "api.unset": "API non configurée", "pullSync": "Synchroniser", "recent": "Récents", "archiveFolder": "Archives", "currentProject": "Projet actuel", "noProject": "Aucun projet", "selectProjectFirst": "Créez ou choisissez un projet", "autoDetectInput": "Détecter la langue", "waitingInput": "En attente", "translate.submit": "Traduire et ajouter", "settings.title": "Réglages", "settings.subtitle": "API, synchronisation et langue de l’interface", "settings.uiLanguage": "Langue de l’interface", "settings.tab.primary": "API principale", "settings.tab.backup": "API de secours", "settings.tab.proxy": "Proxy local", "settings.tab.sync": "Sync", "settings.tab.files": "Fichiers", "projectDialog.newTitle": "Nouveau projet", "projectDialog.editTitle": "Réglages du projet", "projectName": "Nom du projet", "languageLeft": "Langue gauche", "languageRight": "Langue droite", "cancel": "Annuler", "create": "Créer", "save": "Enregistrer", "provider": "Fournisseur", "apiKey": "API Key", "model": "Modèle", "loadModels": "Charger les modèles", "manualModel": "Modèle manuel", "translationStyle": "Style de traduction", "test.connection": "Tester", "test.backup": "Tester secours", "test.sync": "Tester sync", "sync.uploadAll": "Tout envoyer", "uiLanguage.saved": "Langue de l’interface enregistrée."
  },
  de: {
    "settings": "Einstellungen", "newProject": "+ Neues Projekt", "api.unset": "API nicht eingerichtet", "pullSync": "Synchronisieren", "recent": "Zuletzt", "archiveFolder": "Archiv", "currentProject": "Aktuelles Projekt", "noProject": "Noch kein Projekt", "selectProjectFirst": "Erstelle oder wähle zuerst ein Projekt", "autoDetectInput": "Eingabesprache automatisch erkennen", "waitingInput": "Warte auf Eingabe", "translate.submit": "Übersetzen und hinzufügen", "settings.title": "Einstellungen", "settings.subtitle": "Modell-API, Synchronisierung und Sprache", "settings.uiLanguage": "Oberflächensprache", "settings.tab.primary": "Haupt-API", "settings.tab.backup": "Backup-API", "settings.tab.proxy": "Lokaler Proxy", "settings.tab.sync": "Sync", "settings.tab.files": "Dateien", "projectDialog.newTitle": "Neues Projekt", "projectDialog.editTitle": "Projekteinstellungen", "projectName": "Projektname", "languageLeft": "Sprache links", "languageRight": "Sprache rechts", "cancel": "Abbrechen", "create": "Erstellen", "save": "Speichern", "provider": "Anbieter", "apiKey": "API Key", "model": "Modell", "loadModels": "Modelle laden", "manualModel": "Manuelles Modell", "translationStyle": "Übersetzungsstil", "test.connection": "Verbindung testen", "test.backup": "Backup testen", "test.sync": "Sync testen", "sync.uploadAll": "Alles hochladen", "uiLanguage.saved": "Oberflächensprache gespeichert."
  },
  es: {
    "settings": "Ajustes", "newProject": "+ Nuevo proyecto", "api.unset": "API sin configurar", "pullSync": "Sincronizar", "recent": "Recientes", "archiveFolder": "Archivo", "currentProject": "Proyecto actual", "noProject": "Aún no hay proyecto", "selectProjectFirst": "Crea o elige un proyecto primero", "autoDetectInput": "Detectar idioma de entrada", "waitingInput": "Esperando entrada", "translate.submit": "Traducir y añadir", "settings.title": "Ajustes", "settings.subtitle": "API, sincronización e idioma de interfaz", "settings.uiLanguage": "Idioma de interfaz", "settings.tab.primary": "API principal", "settings.tab.backup": "API de respaldo", "settings.tab.proxy": "Proxy local", "settings.tab.sync": "Sync", "settings.tab.files": "Archivos", "projectDialog.newTitle": "Nuevo proyecto", "projectDialog.editTitle": "Ajustes del proyecto", "projectName": "Nombre del proyecto", "languageLeft": "Idioma izquierdo", "languageRight": "Idioma derecho", "cancel": "Cancelar", "create": "Crear", "save": "Guardar", "provider": "Proveedor", "apiKey": "API Key", "model": "Modelo", "loadModels": "Cargar modelos", "manualModel": "Modelo manual", "translationStyle": "Estilo de traducción", "test.connection": "Probar conexión", "test.backup": "Probar respaldo", "test.sync": "Probar sync", "sync.uploadAll": "Subir todo", "uiLanguage.saved": "Idioma de interfaz guardado."
  },
  pt: {
    "settings": "Configurações", "newProject": "+ Novo projeto", "api.unset": "API não configurada", "pullSync": "Sincronizar", "recent": "Recentes", "archiveFolder": "Arquivo", "currentProject": "Projeto atual", "noProject": "Nenhum projeto ainda", "selectProjectFirst": "Crie ou selecione um projeto primeiro", "autoDetectInput": "Detectar idioma de entrada", "waitingInput": "Aguardando entrada", "translate.submit": "Traduzir e adicionar", "settings.title": "Configurações", "settings.subtitle": "API, sincronização e idioma da interface", "settings.uiLanguage": "Idioma da interface", "settings.tab.primary": "API principal", "settings.tab.backup": "API reserva", "settings.tab.proxy": "Proxy local", "settings.tab.sync": "Sync", "settings.tab.files": "Arquivos", "projectDialog.newTitle": "Novo projeto", "projectDialog.editTitle": "Configurações do projeto", "projectName": "Nome do projeto", "languageLeft": "Idioma esquerdo", "languageRight": "Idioma direito", "cancel": "Cancelar", "create": "Criar", "save": "Salvar", "provider": "Provedor", "apiKey": "API Key", "model": "Modelo", "loadModels": "Carregar modelos", "manualModel": "Modelo manual", "translationStyle": "Estilo de tradução", "test.connection": "Testar conexão", "test.backup": "Testar reserva", "test.sync": "Testar sync", "sync.uploadAll": "Enviar tudo", "uiLanguage.saved": "Idioma da interface salvo."
  },
  ru: {
    "settings": "Настройки", "newProject": "+ Новый проект", "api.unset": "API не настроен", "pullSync": "Синхронизация", "recent": "Недавние", "archiveFolder": "Архив", "currentProject": "Текущий проект", "noProject": "Проектов пока нет", "selectProjectFirst": "Сначала создайте или выберите проект", "autoDetectInput": "Определять язык ввода", "waitingInput": "Ожидание ввода", "translate.submit": "Перевести и добавить", "settings.title": "Настройки", "settings.subtitle": "API, синхронизация и язык интерфейса", "settings.uiLanguage": "Язык интерфейса", "settings.tab.primary": "Основной API", "settings.tab.backup": "Резервный API", "settings.tab.proxy": "Локальный прокси", "settings.tab.sync": "Синхр.", "settings.tab.files": "Файлы", "projectDialog.newTitle": "Новый проект", "projectDialog.editTitle": "Настройки проекта", "projectName": "Название проекта", "languageLeft": "Левый язык", "languageRight": "Правый язык", "cancel": "Отмена", "create": "Создать", "save": "Сохранить", "provider": "Провайдер", "apiKey": "API Key", "model": "Модель", "loadModels": "Загрузить модели", "manualModel": "Модель вручную", "translationStyle": "Стиль перевода", "test.connection": "Проверить", "test.backup": "Проверить резерв", "test.sync": "Проверить синхр.", "sync.uploadAll": "Загрузить всё", "uiLanguage.saved": "Язык интерфейса сохранён."
  },
  ar: {
    "settings": "الإعدادات", "newProject": "+ مشروع جديد", "api.unset": "لم يتم إعداد API", "pullSync": "مزامنة", "recent": "الأحدث", "archiveFolder": "الأرشيف", "currentProject": "المشروع الحالي", "noProject": "لا يوجد مشروع بعد", "selectProjectFirst": "أنشئ أو اختر مشروعاً أولاً", "autoDetectInput": "اكتشاف لغة الإدخال", "waitingInput": "بانتظار الإدخال", "translate.submit": "ترجمة وإضافة", "settings.title": "الإعدادات", "settings.subtitle": "API والمزامنة ولغة الواجهة", "settings.uiLanguage": "لغة الواجهة", "settings.tab.primary": "API الأساسي", "settings.tab.backup": "API احتياطي", "settings.tab.proxy": "وكيل محلي", "settings.tab.sync": "مزامنة", "settings.tab.files": "ملفات", "projectDialog.newTitle": "مشروع جديد", "projectDialog.editTitle": "إعدادات المشروع", "projectName": "اسم المشروع", "languageLeft": "لغة اليسار", "languageRight": "لغة اليمين", "cancel": "إلغاء", "create": "إنشاء", "save": "حفظ", "provider": "المزوّد", "apiKey": "API Key", "model": "النموذج", "loadModels": "تحميل النماذج", "manualModel": "نموذج يدوي", "translationStyle": "أسلوب الترجمة", "test.connection": "اختبار الاتصال", "test.backup": "اختبار الاحتياطي", "test.sync": "اختبار المزامنة", "sync.uploadAll": "رفع الكل", "uiLanguage.saved": "تم حفظ لغة الواجهة."
  },
};

const API_PROVIDERS = {
  openai: {
    label: "ChatGPT / OpenAI",
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-4o-mini",
    models: ["gpt-4o-mini", "gpt-4o", "gpt-4.1-mini", "gpt-4.1", "o4-mini"],
  },
  deepseek: {
    label: "DeepSeek",
    baseUrl: "https://api.deepseek.com",
    model: "deepseek-v4-flash",
    models: ["deepseek-v4-flash", "deepseek-v4-pro", "deepseek-chat", "deepseek-reasoner"],
  },
  qwen: {
    label: "千问 / Qwen",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    model: "qwen-mt-plus",
    models: [
      "qwen-mt-plus",
      "qwen-mt-turbo",
      "qwen-plus",
      "qwen-plus-latest",
      "qwen-max",
      "qwen-max-latest",
      "qwen-turbo",
      "qwen-turbo-latest",
      "qwen-flash",
    ],
  },
  gemini: {
    label: "Gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    model: "gemini-2.5-flash",
    models: ["gemini-2.5-flash", "gemini-2.5-pro", "gemini-2.0-flash", "gemini-2.0-flash-lite"],
  },
  custom: {
    label: "自定义",
    baseUrl: "",
    model: "",
    models: [],
  },
};

window.PixelPenguinConfig = {
  languages,
  customLanguageNames,
  uiLanguages,
  languageLocaleCodes,
  uiText,
  DEFAULT_UI_LANGUAGE,
  CUSTOM_LANGUAGE_VALUE: "__custom_language__",
  UI_LANGUAGE_KEY: "pixel-penguin-ui-language-v1",
  STORAGE_KEY: "dialogue-translator-projects-v1",
  API_SETTINGS_KEY: "dialogue-translator-api-settings-v1",
  CLIENT_ID_KEY: "dialogue-translator-client-id-v1",
  FILE_SETTINGS_KEY: "dialogue-translator-file-settings-v1",
  FILE_HANDLE_DB: "dialogue-translator-file-handles",
  FILE_HANDLE_STORE: "handles",
  RECORDS_DIRECTORY_HANDLE_KEY: "records-directory",
  API_PROVIDERS,
  REQUEST_TIMEOUT_MS: 12000,
  PRIMARY_TIMEOUT_LIMIT: 1,
  GIST_SYNC_FILE: "dialogue-translator-sync.json",
  MANUAL_TRANSLATION_DIRECTION_MS: 20 * 60 * 1000,
};
})();
